### ISSUE TITLE
Unable to build with Ubuntu 22.10 and gcc 12.2.0

### ISSUE THREAD

**Issue by dimas1185** [eosnetworkfoundation/eos-evm#548]
there are few errors but here is the first one:

```shell
n file included from /usr/include/c++/12/ios:40,
                 from /usr/include/c++/12/ostream:38,
                 from /usr/include/c++/12/bits/unique_ptr.h:41,
                 from /usr/include/c++/12/memory:76,
                 from /home/dima/.hunter/_Base/10738b5/adf68bd/ff6206a/Build/GTest/Source/googletest/include/gtest/gtest.h:57,
                 from /home/dima/.hunter/_Base/10738b5/adf68bd/ff6206a/Build/GTest/Source/googletest/src/gtest-all.cc:38:
In static member function ‘static constexpr std::char_traits<char>::char_type* std::char_traits<char>::copy(char_type*, const char_type*, std::size_t)’,
    inlined from ‘static constexpr void std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::_S_copy(_CharT*, const _CharT*, size_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’ at /usr/include/c++/12/bits/basic_string.h:423:21,
    inlined from ‘constexpr std::__cxx11::basic_string<_CharT, _Traits, _Allocator>& std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::_M_replace(size_type, size_type, const _CharT*, size_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’ at /usr/include/c++/12/bits/basic_string.tcc:532:22,
    inlined from ‘constexpr std::__cxx11::basic_string<_CharT, _Traits, _Alloc>& std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::replace(size_type, size_type, const _CharT*, size_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’ at /usr/include/c++/12/bits/basic_string.h:2171:19,
    inlined from ‘constexpr std::__cxx11::basic_string<_CharT, _Traits, _Alloc>& std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::insert(size_type, const _CharT*) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’ at /usr/include/c++/12/bits/basic_string.h:1928:22,
    inlined from ‘constexpr std::__cxx11::basic_string<_CharT, _Traits, _Allocator> std::operator+(const _CharT*, __cxx11::basic_string<_CharT, _Traits, _Allocator>&&) [with _CharT = char; _Traits = char_traits<char>; _Alloc = allocator<char>]’ at /usr/include/c++/12/bits/basic_string.h:3541:36,
    inlined from ‘static std::string testing::internal::StreamingListener::UrlEncode(const char*)’ at /home/dima/.hunter/_Base/10738b5/adf68bd/ff6206a/Build/GTest/Source/googletest/src/gtest.cc:4882:27:
/usr/include/c++/12/bits/char_traits.h:431:56: error: ‘void* __builtin_memcpy(void*, const void*, long unsigned int)’ accessing 9223372036854775810 or more bytes at offsets [2, 9223372036854775807] and 1 may overlap up to 9223372036854775813 bytes at offset -3 [-Werror=restrict]
  431 |         return static_cast<char_type*>(__builtin_memcpy(__s1, __s2, __n));
      |                                        ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
```

**Comment by BenjaminGormanPMP** [comment]
Setup technical planning meeting with Matias and Dmytro to review – Unable to build with Ubuntu 22.10 and gcc 12.2.0 #548.
	https://github.com/eosnetworkfoundation/eos-evm/issues/548 
	Post-meeting update – moved to blocked status pending completion for EMV update silkworm to latest version #589 
o	https://github.com/eosnetworkfoundation/eos-evm/issues/589

**Comment by elmato** [comment]
Building with g++12 fails with the following error

```
eos-evm-node/external/silkworm/silkworm/silkrpc/http/server.cpp: In member function ‘boost::asio::awaitable<void> silkworm::rpc::http::Server::run()’:
eos-evm-node/external/silkworm/silkworm/silkrpc/http/server.cpp:94:21: error: await expressions are not permitted in handlers
   94 |                     co_await timer.async_wait(boost::asio::use_awaitable);
      |                     ^~~~~~~~
```
